CC=g++

all: apuntador memoria lifetimes dinamica referencias ejemplo_listas

apuntador: apuntador.cpp
	$(CC) apuntador.cpp -o apuntador

memoria: memoria.cpp
	$(CC) memoria.cpp -o memoria

lifetimes: lifetimes.cpp
	$(CC) lifetimes.cpp -o lifetimes

dinamica: dinamica.cpp
	$(CC) dinamica.cpp -o dinamica

referencias: referencias.cpp
	$(CC) referencias.cpp -o referencias

ejemplo_listas: ejemplo_listas.cpp
	$(CC) ejemplo_listas.cpp -o ejemplo_listas

clean:
	rm -f apuntador memoria lifetimes dinamica
