CC=g++

all: apuntador memoria lifetimes dinamica

apuntador: apuntador.cpp
	$(CC) apuntador.cpp -o apuntador

memoria: memoria.cpp
	$(CC) memoria.cpp -o memoria

lifetimes: lifetimes.cpp
	$(CC) lifetimes.cpp -o lifetimes

dinamica: dinamica.cpp
	$(CC) dinamica.cpp -o dinamica

clean:
	rm -f apuntador memoria lifetimes dinamica
